### ISSUE TITLE
DEBUG不是内部指令

### ISSUE THREAD

**Issue by TheCornerOfTheWorld** [baozouai/vite-plugin-alias-import-checker#1]
安装完毕 pnpm i 
执行 pnpm play
抛出错误
''DEBUG' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by baozouai** [comment]
> 安装完毕 pnpm i 执行 pnpm play 抛出错误 ''DEBUG' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

@TheCornerOfTheWorld 拉下main最新代码
